# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QDockWidget, QGridLayout,
    QHBoxLayout, QHeaderView, QLabel, QListWidget,
    QListWidgetItem, QMainWindow, QMenu, QMenuBar,
    QPlainTextEdit, QSizePolicy, QStatusBar, QTabWidget,
    QTreeView, QVBoxLayout, QWidget)

from mplwidget import MplWidget
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.resize(1058, 737)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/icons/app_icon.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedKingdom))
        MainWindow.setTabShape(QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionOpen_Workfolder = QAction(MainWindow)
        self.actionOpen_Workfolder.setObjectName(u"actionOpen_Workfolder")
        icon1 = QIcon()
        icon1.addFile(u":/linea_icons/resources/linea_basic_icons/basic_folder.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen_Workfolder.setIcon(icon1)
        self.actionProcessingMenu = QAction(MainWindow)
        self.actionProcessingMenu.setObjectName(u"actionProcessingMenu")
        self.actionProcessingMenu.setEnabled(True)
        self.actionSignalNavigation = QAction(MainWindow)
        self.actionSignalNavigation.setObjectName(u"actionSignalNavigation")
        self.actionSignalNavigation.setEnabled(True)
        self.actionDictionary_indexing = QAction(MainWindow)
        self.actionDictionary_indexing.setObjectName(u"actionDictionary_indexing")
        self.actionPattern_Center = QAction(MainWindow)
        self.actionPattern_Center.setObjectName(u"actionPattern_Center")
        self.actionROI = QAction(MainWindow)
        self.actionROI.setObjectName(u"actionROI")
        self.actionHough_indexing = QAction(MainWindow)
        self.actionHough_indexing.setObjectName(u"actionHough_indexing")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon2 = QIcon()
        icon2.addFile(u":/linea_icons/resources/linea_basic_icons/basic_gear.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSettings.setIcon(icon2)
        self.actionImage_quality = QAction(MainWindow)
        self.actionImage_quality.setObjectName(u"actionImage_quality")
        self.actionMean_intensity = QAction(MainWindow)
        self.actionMean_intensity.setObjectName(u"actionMean_intensity")
        self.actionVirtual_backscatter_electron = QAction(MainWindow)
        self.actionVirtual_backscatter_electron.setObjectName(u"actionVirtual_backscatter_electron")
        self.actionAverage_dot_product = QAction(MainWindow)
        self.actionAverage_dot_product.setObjectName(u"actionAverage_dot_product")
        self.actionGenerate_images = QAction(MainWindow)
        self.actionGenerate_images.setObjectName(u"actionGenerate_images")
        self.actionGenerate_images.setEnabled(False)
        font = QFont()
        font.setKerning(False)
        font.setStyleStrategy(QFont.NoAntialias)
        self.actionGenerate_images.setFont(font)
        self.actionGenerate_images.setMenuRole(QAction.NoRole)
        self.actionToggleSystem_Explorer = QAction(MainWindow)
        self.actionToggleSystem_Explorer.setObjectName(u"actionToggleSystem_Explorer")
        self.actionToggleSystem_Explorer.setCheckable(True)
        self.actionToggleSystem_Explorer.setChecked(True)
        self.actionToggleTerminal = QAction(MainWindow)
        self.actionToggleTerminal.setObjectName(u"actionToggleTerminal")
        self.actionToggleTerminal.setCheckable(True)
        self.actionToggleTerminal.setChecked(True)
        self.actionToggleImage_Viewer = QAction(MainWindow)
        self.actionToggleImage_Viewer.setObjectName(u"actionToggleImage_Viewer")
        self.actionToggleImage_Viewer.setCheckable(True)
        self.actionToggleImage_Viewer.setChecked(True)
        self.actionToggleJob_Manager = QAction(MainWindow)
        self.actionToggleJob_Manager.setObjectName(u"actionToggleJob_Manager")
        self.actionToggleJob_Manager.setCheckable(True)
        self.actionToggleJob_Manager.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1058, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuProcessing = QMenu(self.menubar)
        self.menuProcessing.setObjectName(u"menuProcessing")
        self.menuProcessing.setEnabled(False)
        self.menuPlot = QMenu(self.menubar)
        self.menuPlot.setObjectName(u"menuPlot")
        self.menuPlot.setEnabled(False)
        self.menuPre_indexing_maps = QMenu(self.menuPlot)
        self.menuPre_indexing_maps.setObjectName(u"menuPre_indexing_maps")
        self.menuPre_indexing_maps.setEnabled(False)
        self.menuIndexing = QMenu(self.menubar)
        self.menuIndexing.setObjectName(u"menuIndexing")
        self.menuIndexing.setEnabled(False)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.dockWidgetTerminal = QDockWidget(MainWindow)
        self.dockWidgetTerminal.setObjectName(u"dockWidgetTerminal")
        self.dockWidgetTerminalContents = QWidget()
        self.dockWidgetTerminalContents.setObjectName(u"dockWidgetTerminalContents")
        self.gridLayout_2 = QGridLayout(self.dockWidgetTerminalContents)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.consoleLog = QPlainTextEdit(self.dockWidgetTerminalContents)
        self.consoleLog.setObjectName(u"consoleLog")
        sizePolicy1 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.consoleLog.sizePolicy().hasHeightForWidth())
        self.consoleLog.setSizePolicy(sizePolicy1)

        self.verticalLayout_3.addWidget(self.consoleLog)

        self.inputLayout = QHBoxLayout()
        self.inputLayout.setObjectName(u"inputLayout")
        self.consolePrompt = QLabel(self.dockWidgetTerminalContents)
        self.consolePrompt.setObjectName(u"consolePrompt")

        self.inputLayout.addWidget(self.consolePrompt)


        self.verticalLayout_3.addLayout(self.inputLayout)

        self.verticalLayout_3.setStretch(0, 1)

        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.dockWidgetTerminal.setWidget(self.dockWidgetTerminalContents)
        MainWindow.addDockWidget(Qt.BottomDockWidgetArea, self.dockWidgetTerminal)
        self.dockWidgetSystemExplorer = QDockWidget(MainWindow)
        self.dockWidgetSystemExplorer.setObjectName(u"dockWidgetSystemExplorer")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.dockWidgetSystemExplorer.sizePolicy().hasHeightForWidth())
        self.dockWidgetSystemExplorer.setSizePolicy(sizePolicy2)
        self.dockWidgetSystemExplorerContents = QWidget()
        self.dockWidgetSystemExplorerContents.setObjectName(u"dockWidgetSystemExplorerContents")
        self.gridLayout = QGridLayout(self.dockWidgetSystemExplorerContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.systemViewerLayout = QVBoxLayout()
        self.systemViewerLayout.setObjectName(u"systemViewerLayout")
        self.folderLabel = QLabel(self.dockWidgetSystemExplorerContents)
        self.folderLabel.setObjectName(u"folderLabel")
        sizePolicy.setHeightForWidth(self.folderLabel.sizePolicy().hasHeightForWidth())
        self.folderLabel.setSizePolicy(sizePolicy)

        self.systemViewerLayout.addWidget(self.folderLabel)

        self.systemViewer = QTreeView(self.dockWidgetSystemExplorerContents)
        self.systemViewer.setObjectName(u"systemViewer")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.systemViewer.sizePolicy().hasHeightForWidth())
        self.systemViewer.setSizePolicy(sizePolicy3)
        self.systemViewer.setMinimumSize(QSize(320, 320))
        self.systemViewer.setMouseTracking(False)
        self.systemViewer.setTabletTracking(True)
        self.systemViewer.setStyleSheet(u"")
        self.systemViewer.setEditTriggers(QAbstractItemView.AnyKeyPressed|QAbstractItemView.CurrentChanged|QAbstractItemView.DoubleClicked|QAbstractItemView.SelectedClicked)
        self.systemViewer.setTabKeyNavigation(True)
        self.systemViewer.setDragEnabled(False)
        self.systemViewer.setDragDropOverwriteMode(False)
        self.systemViewer.setAlternatingRowColors(False)
        self.systemViewer.setAnimated(True)
        self.systemViewer.header().setStretchLastSection(True)

        self.systemViewerLayout.addWidget(self.systemViewer)


        self.gridLayout.addLayout(self.systemViewerLayout, 0, 0, 1, 1)

        self.dockWidgetSystemExplorer.setWidget(self.dockWidgetSystemExplorerContents)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.dockWidgetSystemExplorer)
        self.dockWidgetImageViewer = QDockWidget(MainWindow)
        self.dockWidgetImageViewer.setObjectName(u"dockWidgetImageViewer")
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy4.setHorizontalStretch(10)
        sizePolicy4.setVerticalStretch(10)
        sizePolicy4.setHeightForWidth(self.dockWidgetImageViewer.sizePolicy().hasHeightForWidth())
        self.dockWidgetImageViewer.setSizePolicy(sizePolicy4)
        self.dockWidgetContentsImageViewer = QWidget()
        self.dockWidgetContentsImageViewer.setObjectName(u"dockWidgetContentsImageViewer")
        sizePolicy.setHeightForWidth(self.dockWidgetContentsImageViewer.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsImageViewer.setSizePolicy(sizePolicy)
        self.gridLayout_4 = QGridLayout(self.dockWidgetContentsImageViewer)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.MplWidget = MplWidget(self.dockWidgetContentsImageViewer)
        self.MplWidget.setObjectName(u"MplWidget")
        sizePolicy5 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy5)
        self.MplWidget.setMinimumSize(QSize(320, 320))
        self.MplWidget.setAutoFillBackground(False)
        self.MplWidget.setStyleSheet(u"background-color: transparent")

        self.gridLayout_4.addWidget(self.MplWidget, 0, 0, 1, 1)

        self.dockWidgetImageViewer.setWidget(self.dockWidgetContentsImageViewer)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.dockWidgetImageViewer)
        self.dockWidgetJobManager = QDockWidget(MainWindow)
        self.dockWidgetJobManager.setObjectName(u"dockWidgetJobManager")
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout_3 = QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.jobList = QListWidget(self.dockWidgetContents)
        self.jobList.setObjectName(u"jobList")
        self.jobList.setSelectionMode(QAbstractItemView.NoSelection)

        self.gridLayout_3.addWidget(self.jobList, 1, 0, 1, 1)

        self.threadsLabel = QLabel(self.dockWidgetContents)
        self.threadsLabel.setObjectName(u"threadsLabel")
        self.threadsLabel.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.gridLayout_3.addWidget(self.threadsLabel, 0, 0, 1, 1)

        self.dockWidgetJobManager.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.TopDockWidgetArea, self.dockWidgetJobManager)
        self.dockWidgetTerminal.raise_()
        self.dockWidgetSystemExplorer.raise_()
        self.dockWidgetImageViewer.raise_()
        self.dockWidgetJobManager.raise_()
        QWidget.setTabOrder(self.systemViewer, self.consoleLog)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuProcessing.menuAction())
        self.menubar.addAction(self.menuPlot.menuAction())
        self.menubar.addAction(self.menuIndexing.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionOpen_Workfolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuProcessing.addAction(self.actionProcessingMenu)
        self.menuProcessing.addAction(self.actionROI)
        self.menuProcessing.addAction(self.actionPattern_Center)
        self.menuPlot.addAction(self.actionSignalNavigation)
        self.menuPlot.addAction(self.menuPre_indexing_maps.menuAction())
        self.menuPre_indexing_maps.addAction(self.actionAverage_dot_product)
        self.menuPre_indexing_maps.addAction(self.actionImage_quality)
        self.menuPre_indexing_maps.addAction(self.actionMean_intensity)
        self.menuPre_indexing_maps.addAction(self.actionVirtual_backscatter_electron)
        self.menuIndexing.addAction(self.actionDictionary_indexing)
        self.menuIndexing.addAction(self.actionHough_indexing)
        self.menuView.addAction(self.actionToggleSystem_Explorer)
        self.menuView.addAction(self.actionToggleTerminal)
        self.menuView.addAction(self.actionToggleImage_Viewer)
        self.menuView.addAction(self.actionToggleJob_Manager)

        self.retranslateUi(MainWindow)
        self.dockWidgetTerminal.visibilityChanged.connect(self.actionToggleTerminal.setChecked)
        self.dockWidgetSystemExplorer.visibilityChanged.connect(self.actionToggleSystem_Explorer.setChecked)
        self.actionToggleSystem_Explorer.triggered["bool"].connect(self.dockWidgetSystemExplorer.setVisible)
        self.actionToggleTerminal.triggered["bool"].connect(self.dockWidgetTerminal.setVisible)
        self.actionToggleImage_Viewer.triggered["bool"].connect(self.dockWidgetImageViewer.setVisible)
        self.dockWidgetImageViewer.visibilityChanged.connect(self.actionToggleImage_Viewer.setChecked)
        self.dockWidgetJobManager.visibilityChanged.connect(self.actionToggleJob_Manager.setChecked)
        self.actionToggleJob_Manager.triggered["bool"].connect(self.dockWidgetJobManager.setVisible)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"EBSD-GUI", None))
        self.actionOpen_Workfolder.setText(QCoreApplication.translate("MainWindow", u"Open Workfolder...", None))
#if QT_CONFIG(statustip)
        self.actionOpen_Workfolder.setStatusTip(QCoreApplication.translate("MainWindow", u"Select a folder containing patterns", u"LOL"))
#endif // QT_CONFIG(statustip)
        self.actionProcessingMenu.setText(QCoreApplication.translate("MainWindow", u"Signal-to-noise improvement", None))
#if QT_CONFIG(statustip)
        self.actionProcessingMenu.setStatusTip(QCoreApplication.translate("MainWindow", u"Perform processing on a pattern", None))
#endif // QT_CONFIG(statustip)
        self.actionSignalNavigation.setText(QCoreApplication.translate("MainWindow", u"Signal navigation", None))
        self.actionDictionary_indexing.setText(QCoreApplication.translate("MainWindow", u"Dictionary indexing", None))
        self.actionPattern_Center.setText(QCoreApplication.translate("MainWindow", u"Refine pattern center", None))
        self.actionROI.setText(QCoreApplication.translate("MainWindow", u"Region of interest", None))
        self.actionHough_indexing.setText(QCoreApplication.translate("MainWindow", u"Hough indexing", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
#if QT_CONFIG(statustip)
        self.actionSettings.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.actionImage_quality.setText(QCoreApplication.translate("MainWindow", u"Image quality map", None))
        self.actionMean_intensity.setText(QCoreApplication.translate("MainWindow", u"Mean intensity map", None))
        self.actionVirtual_backscatter_electron.setText(QCoreApplication.translate("MainWindow", u"Virtual backscatter electron", None))
        self.actionAverage_dot_product.setText(QCoreApplication.translate("MainWindow", u"Average dot product", None))
        self.actionGenerate_images.setText(QCoreApplication.translate("MainWindow", u"Generate images...", None))
        self.actionToggleSystem_Explorer.setText(QCoreApplication.translate("MainWindow", u"System Explorer", None))
        self.actionToggleTerminal.setText(QCoreApplication.translate("MainWindow", u"Terminal", None))
        self.actionToggleImage_Viewer.setText(QCoreApplication.translate("MainWindow", u"Image Viewer", None))
        self.actionToggleJob_Manager.setText(QCoreApplication.translate("MainWindow", u"Job Manager", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuProcessing.setTitle(QCoreApplication.translate("MainWindow", u"Processing", None))
        self.menuPlot.setTitle(QCoreApplication.translate("MainWindow", u"Pattern inspection", None))
        self.menuPre_indexing_maps.setTitle(QCoreApplication.translate("MainWindow", u"Pre-indexing maps", None))
        self.menuIndexing.setTitle(QCoreApplication.translate("MainWindow", u"Indexing", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.dockWidgetTerminal.setWindowTitle(QCoreApplication.translate("MainWindow", u"Terminal", None))
        self.consolePrompt.setText(QCoreApplication.translate("MainWindow", u">>>", None))
        self.dockWidgetSystemExplorer.setWindowTitle(QCoreApplication.translate("MainWindow", u"System Viewer", None))
        self.folderLabel.setText(QCoreApplication.translate("MainWindow", u"NO FOLDER OPENED", None))
        self.dockWidgetImageViewer.setWindowTitle(QCoreApplication.translate("MainWindow", u"Image Viewer", None))
        self.dockWidgetJobManager.setWindowTitle(QCoreApplication.translate("MainWindow", u"Job Manager", None))
        self.threadsLabel.setText(QCoreApplication.translate("MainWindow", u"0 out of 0 active jobs", None))
    # retranslateUi

