# Form implementation generated from reading ui file '/Users/olavletholsen/EBSD-data/EBSD-GUI-olavlet/ui/pattern_processing_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PatternProcessingWindow(object):
    def setupUi(self, PatternProcessingWindow):
        PatternProcessingWindow.setObjectName("PatternProcessingWindow")
        PatternProcessingWindow.resize(803, 228)
        self.gridLayout_2 = QtWidgets.QGridLayout(PatternProcessingWindow)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.centralwidget = QtWidgets.QFrame(PatternProcessingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.dynamicBackgroundBox = QtWidgets.QCheckBox(self.centralwidget)
        self.dynamicBackgroundBox.setChecked(True)
        self.dynamicBackgroundBox.setObjectName("dynamicBackgroundBox")
        self.gridLayout.addWidget(self.dynamicBackgroundBox, 2, 0, 1, 1)
        self.pathLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.pathLineEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.gridLayout.addWidget(self.pathLineEdit, 5, 1, 1, 1)
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pathLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.pathLabel.setObjectName("pathLabel")
        self.gridLayout.addWidget(self.pathLabel, 5, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 1)
        self.averageBox = QtWidgets.QCheckBox(self.centralwidget)
        self.averageBox.setChecked(True)
        self.averageBox.setObjectName("averageBox")
        self.gridLayout.addWidget(self.averageBox, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 200, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setEnabled(True)
        self.browseButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.browseButton.setAutoFillBackground(False)
        self.browseButton.setObjectName("browseButton")
        self.gridLayout.addWidget(self.browseButton, 5, 2, 1, 1)
        self.staticBackgroundBox = QtWidgets.QCheckBox(self.centralwidget)
        self.staticBackgroundBox.setChecked(True)
        self.staticBackgroundBox.setTristate(False)
        self.staticBackgroundBox.setObjectName("staticBackgroundBox")
        self.gridLayout.addWidget(self.staticBackgroundBox, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout_2.addWidget(self.centralwidget, 0, 0, 1, 1)

        self.retranslateUi(PatternProcessingWindow)
        QtCore.QMetaObject.connectSlotsByName(PatternProcessingWindow)

    def retranslateUi(self, PatternProcessingWindow):
        _translate = QtCore.QCoreApplication.translate
        PatternProcessingWindow.setWindowTitle(_translate("PatternProcessingWindow", "Pattern Processing"))
        self.dynamicBackgroundBox.setWhatsThis(_translate("PatternProcessingWindow", "Remove the dynamic background in an EBSD pattern."))
        self.dynamicBackgroundBox.setText(_translate("PatternProcessingWindow", "Remove dynamic background noise"))
        self.pathLabel.setText(_translate("PatternProcessingWindow", "Filepath of processed pattern:"))
        self.averageBox.setWhatsThis(_translate("PatternProcessingWindow", "Average a chunk of patterns with its neighbours within a window."))
        self.averageBox.setText(_translate("PatternProcessingWindow", "Average neighbour patterns"))
        self.browseButton.setText(_translate("PatternProcessingWindow", "Browse"))
        self.staticBackgroundBox.setWhatsThis(_translate("PatternProcessingWindow", "Remove the static background inplace."))
        self.staticBackgroundBox.setText(_translate("PatternProcessingWindow", "Remove static background noise"))
