# Form implementation generated from reading ui file '/Users/olavletholsen/EBSD-data/EBSD-GUI-olavlet/ui/remove_background.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pattern_Processing(object):
    def setupUi(self, Pattern_Processing):
        Pattern_Processing.setObjectName("Pattern_Processing")
        Pattern_Processing.resize(272, 197)
        self.centralwidget = QtWidgets.QWidget(Pattern_Processing)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        Pattern_Processing.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Pattern_Processing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 272, 24))
        self.menubar.setObjectName("menubar")
        Pattern_Processing.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Pattern_Processing)
        self.statusbar.setObjectName("statusbar")
        Pattern_Processing.setStatusBar(self.statusbar)

        self.retranslateUi(Pattern_Processing)
        QtCore.QMetaObject.connectSlotsByName(Pattern_Processing)

    def retranslateUi(self, Pattern_Processing):
        _translate = QtCore.QCoreApplication.translate
        Pattern_Processing.setWindowTitle(_translate("Pattern_Processing", "MainWindow"))
        self.checkBox_3.setText(_translate("Pattern_Processing", "CheckBox"))
        self.checkBox.setText(_translate("Pattern_Processing", "CheckBox"))
        self.pushButton.setText(_translate("Pattern_Processing", "PushButton"))
        self.checkBox_2.setText(_translate("Pattern_Processing", "CheckBox"))
